### ISSUE TITLE
extenda/actions/rs-create-installerpkg - fails when using multiple builder-type

### ISSUE THREAD

**Issue by ostsmolynets** [extenda/actions#128]
When using the following setup:
```
- name: Create installer packages for vri jobs      
  uses: extenda/actions/rs-create-installerpkg@v0      
  with:        
    builder-type: multiple        
    tool-version: 1.1.0        
    working-dir: .        
    output-dir: installpackages_jobs        
    source-paths: Item\VriPackages        
    package-version: ${{ steps.semver.outputs.version }}      
  env:        
    NEXUS_USERNAME: ${{ env.NEXUS_USERNAME }}        
    NEXUS_PASSWORD: ${{ env.NEXUS_PASSWORD }}
```
The error appears:
C:\hostedtoolcache\windows\InstallerPackageBuilder.Core.Console\1.1.0\x64\InstallerPackageBuilder.Core.Console.exe multiple -pn "" -wd . -od installpackages_jobs -pv 0.0.1-6 -sp Item\VriPackages
Debug: Starting InstallerPackageBuilder... (InstallerPackageBuilder.Core.Console.Program[0])
'-pn' was not matched. Did you mean '-pv'?
'' was not matched. Did you mean 'wd', or 'od', or 'sp', or 'pv'?
Unrecognized command or argument '-pn'
Unrecognized command or argument ''
![image](https://user-images.githubusercontent.com/62648334/83608666-e3d76900-a585-11ea-998f-9d1208740cae.png)
