### ISSUE TITLE
Multiple to multiple source RS installer packages fail

### ISSUE THREAD

**Issue by l0kal** [extenda/actions#269]
If you add multiple sources with multiple input flag eg.
The first will succeed since it only loops over the first source path. While if you try the same over the list of source paths it will not be able to find all packages created.

  ```
 - name: Create vri jobs installer packages TEST
      uses: extenda/actions/rs-create-installerpkg@v0
      with:
        builder-type: multiple
        tool-version: 1.1.0
        working-dir: .
        output-dir: installpackages_jobs
        source-paths: |
          Source\SuperPosService\VriPackages
        package-version: ${{ steps.semver.outputs.semver }}
        publish-package: true
        publish-root-url: https://repo.extendaretail.com/repository/raw-hosted/RS/
        branch-name-short: ${{ steps.semver.outputs.branch-name-short }}
      env:
        NEXUS_USERNAME: ${{ env.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ env.NEXUS_PASSWORD }}

    - name: Create vri jobs installer packages
      uses: extenda/actions/rs-create-installerpkg@v0
      with:
        builder-type: multiple
        tool-version: 1.1.0
        working-dir: .
        output-dir: installpackages_jobs
        source-paths: |
          Source\SuperPosService\AccountService\VriPackages
          Source\SuperPosService\CommandService\VriPackages
          Source\SuperPosService\DataService\VriPackages
          Source\SuperPosService\InventoryService\VriPackages
          Source\SuperPosService\OperatorService\VriPackages
          Source\SuperPosService\PosClientService\VriPackages
          Source\SuperPosService\ReceiptService\VriPackages
          Source\SuperPosService\TotalsService\VriPackages
          Source\SuperPosService\UtilityService\VriPackages
        package-version: ${{ steps.semver.outputs.semver }}
        publish-package: true
        publish-root-url: https://repo.extendaretail.com/repository/raw-hosted/RS/
        branch-name-short: ${{ steps.semver.outputs.branch-name-short }}
      env:
        NEXUS_USERNAME: ${{ env.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ env.NEXUS_PASSWORD }}
```

const fullPath = sourcePaths; // path.join(__dirname, sourcePaths); would in the second case use all paths, but not loop correctly over them. Could the solution be to loop over the parent source directories before looping over the directories to get the filenames? 
```
const buildPackage = async (args) => {
  const {
    builderType,
    publishPackage,
    packageVersion,
    outputDir,
    publishUrl,
    branch,
    sourcePaths,
  } = args;

  const buildTool = await downloadBuildTool(args);
  await packageBuilderCommand(buildTool, args);
  if (publishPackage) {
    if (builderType === 'multiple') {
      const fullPath = sourcePaths; // path.join(__dirname, sourcePaths);
      core.info(`Sourcepath fullname: ${fullPath}`);
      const dirs = fs.readdirSync(fullPath)
        .filter((f) => fs.statSync(path.join(fullPath, f)).isDirectory());
      dirs.forEach((dir) => {
        core.info(`DirectoryName: ${dir}`);
        publishPackageCommand({
          packageName: dir,
          packageVersion,
          outputDir,
          publishUrl,
          branch,
        });
      });
    } else {
      publishPackageCommand(args);
    }
  }
  return true;
};
```
